# Generated by Django 5.2.1 on 2025-06-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vehiculo', models.TextField(verbose_name='tipo_vehiuculo')),
                ('placa_vehiculo', models.TextField(verbose_name='placa_vehiculo')),
                ('h_d_m', models.IntegerField(verbose_name='h_d_m')),
                ('login_id', models.IntegerField(verbose_name='login')),
            ],
        ),
    ]
