# Generated by Django 5.2.3 on 2025-06-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tarifas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moto', models.TextField(verbose_name='moto')),
                ('carro', models.TextField(verbose_name='carro')),
                ('vip', models.TextField(verbose_name='vip')),
            ],
        ),
    ]
