# Generated by Django 5.2.3 on 2025-06-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.TextField(verbose_name='ticket')),
                ('entrada_id', models.IntegerField(verbose_name='entrada')),
            ],
        ),
    ]
