# Generated by Django 5.2.3 on 2025-06-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='contraseña',
            field=models.TextField(verbose_name='contraseña'),
        ),
        migrations.AlterField(
            model_name='login',
            name='correo',
            field=models.TextField(verbose_name='correo'),
        ),
    ]
